source 'https://github.com/CocoaPods/Specs.git'



 
platform :ios, '12.1'

use_frameworks!
   
target 'Wishlist' do
    pod 'AWSAppSync'
    pod 'AWSAPIGateway'
    pod 'AWSMobileClient'
    pod 'AWSAuthUI'
    pod 'AWSUserPoolsSignIn'

end

